### PR TITLE
config: add missing functions for completeness

### PR DESCRIPTION
**Pull request by MichaelMure**
This PR complete the Config functions.

Add Options.Has to check if an Option exist.

Wherever a collection of Option exist, make sure that the following functions exists as well:
- Option
- OptionAll (new, return all values)
- HasOption (new)
- AddOption
- SetOption
- RemoveOption

For Config and Section, make sure that the following exist to access the sublevel:
- X
- HasX (HasSection was missing)
- RemoveX (RemoveSubsection was missing)

This PR also does some shuffling to have a consistent ordering of functions.

### CODE REVIEW

**Comment by mcuadros** [comment]
This is awesome can you add tests for this?

**Comment by MichaelMure** [comment]
Holiday is over, not sure I'll have the freedom anytime soon :-|

**Comment by MichaelMure** [comment]
@mcuadros 

@Invincibot added the needed tests, can we merge ?

**Comment by MichaelMure** [comment]
CI failure is unrelated to this PR.

**Comment by MichaelMure** [comment]
Anyone?

**Comment by mcuadros** [comment]
Sorry for the delay, weird times.

**Comment by MichaelMure** [comment]
Thank you :-)

**Pull request merged**
