### PR TITLE
config: support insteadOf for remotes' URLs

### PR DESCRIPTION
**Pull request by kostyay**
Added support for insteadOf configuration for remote's urls. 
Can also be applied to submodules, but I didn't implement that.

This fixes: https://github.com/go-git/go-git/issues/76

### CODE REVIEW

**Comment by mcuadros** [comment]
Great! I have a big concern if you check how behaves git, with instead, it is straight forward. The `insteadOf` just happens in the clone operation, so once that the clone happens, the original URL is gone. So you don't need to keep track of it in the remote or something similar.

So I believe that we need to check the global/system configuration in the `git.Clone` and apply the URL, and the left the remote as it is right now.

Additionally, we should at an option in `CloneOptions` to allow enable or disable this behavior. (By default disable)

**Comment by kostyay** [comment]
ok, i will update the pr

**Comment by aca** [comment]
@kostyay 
This will be definitely useful. Any updates on this?

**Comment by kostyay** [comment]
I didn't have time to rewrite it yet.
I will see if I can get to it this weekend.

**Comment by kostyay** [comment]
> Great! I have a big concern if you check how behaves git, with instead, it is straight forward. The `insteadOf` just happens in the clone operation, so once that the clone happens, the original URL is gone. So you don't need to keep track of it in the remote or something similar.
> 
> So I believe that we need to check the global/system configuration in the `git.Clone` and apply the URL, and the left the remote as it is right now.
> 
> Additionally, we should at an option in `CloneOptions` to allow enable or disable this behavior. (By default disable)

From what I see, ~/.gitconfig is not loaded when `Clone` function is called. So that will have to be fixed as well, because in normal use case AFAIK, the `insteadOf` is configured on the global scope before a repository is cloned.
Any tips how to approach that?
I saw the readme states `Reading and modifying per-repository configuration (.git/config) is supported. Global configuration ($HOME/.gitconfig) is not.`

**Comment by kostyay** [comment]
@mcuadros I've updated the implementation following your comments.
Let me know what you think.

**Comment by kamaln7** [comment]
Hey, sorry that I'm being this person, but based on the discussion I feel like this slipped through the cracks. Any chance it could be reviewed again? Thank you!

**Comment by kostyay** [comment]
> Hey, sorry that I'm being this person, but based on the discussion I feel like this slipped through the cracks. Any chance it could be reviewed again? Thank you!

The repo maintainer never bothered reviewing it

**Comment by mcuadros** [comment]
LGTM can you fix the conflicts @kostyay ?

**Comment by kostyay** [comment]
Fixed

**Comment by kostyay** [comment]
Not sure why tests are failing.. flaky?

**Comment by mcuadros** [comment]
Yup is a flaky test.

**Pull request merged**
