### PR TITLE
Fetch submodules pointing to orphaned but still reachable commits

### PR DESCRIPTION
**Pull request by edigaryev**
Sometimes submodules are not updated for long periods of time and the tree that holds the commit they point to gets removed at some point, which results in commits that are orphaned, but still reachable using [`allow-reachable-sha1-in-want`](https://git-scm.com/docs/protocol-capabilities#_allow_reachable_sha1_in_want) Git's wire protocol capability.

Here's a real case: https://github.com/cirruslabs/cirrus-ci-docs/pull/830#issuecomment-812618218.

This change makes sure go-git will behave similarly to Git in such cases, which [does a subsequent fetch](https://github.com/git/git/blob/080627942802e767b068a491f3d349227f4e2cdc/submodule.c#L1571-L1577) using a commit hash.

### CODE REVIEW

**Comment by fkorotkov** [comment]
@mcuadros, gentle ping. I'll appreciate if you could take a look. This fix will help FreeBSD folks test FreeBSD on Cirrus CI faster.

**Comment by mcuadros** [comment]
any chance to do a test?

**Comment by edigaryev** [comment]
> any chance to do a test?

Sure, if you don't mind accepting a PR with a single commit first and then dropping the tree it belongs to.

I assume I'll need to create a PR in https://github.com/git-fixtures/basic?

**Comment by mcuadros** [comment]
Yup

**Comment by edigaryev** [comment]
> Yup, there is a submodule fixture but maybe is not enough.

Well, OK 🤷 

It seems that the `TestResolveRevision` is failing on `master`, any idea if this might be related to this PR?

**Pull request merged**
