### PR TITLE
Add SECURITY.md

### LINKED ISSUE #527: Who to contact for security issues
Hey there!

I belong to an open source security research community, and a member (@ry0tak) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

### PR DESCRIPTION
**Pull request by pjbgf**
Fixes #527 #543

### CODE REVIEW

**Comment by AriehSchneier** [comment]
Fixes #527

**Comment by AriehSchneier** [comment]
Fixes #543

**Comment by pjbgf** [comment]
@AriehSchneier nice one, updated the commit message accordingly.

**Review by hiddeco — APPROVED** [review]
Long due, thanks @pjbgf :bow:

**Pull request merged**
