### PR TITLE
resolve external references when cloning a remote delta enabled repo.

### PR DESCRIPTION
**Pull request by bashims**
Signed-off-by: Benjamin Ash <bash@intelerad.com>

### CODE REVIEW

**Comment by bassofed** [comment]
This PR solves [This issue](https://github.com/go-git/go-git/issues/336)

Why is it marked as "work in progress" for so long?

**Comment by thefang12** [comment]
I'm also affected by  [this issue](https://github.com/go-git/go-git/issues/336) any ETA on getting this released? 🙏

**Comment by JasonMKurtz** [comment]
@bashims This PR unblocks the issue for me (and some other people, it seems, too). What is blocking this from being published and merged?

**Comment by per1234** [comment]
This can be closed as superseded by https://github.com/go-git/go-git/pull/392
Thanks so much for your fix **[bashims](https://github.com/bashims)** and **[ga-paul-t](https://github.com/ga-paul-t)**!

**Pull request closed without merging**
