### PR TITLE
Add Merge with ff-only

### PR DESCRIPTION
**Pull request by john-cai**
Add a Merge function that behaves like git merge. This is a first
iteration that only supports --ff-only, which is the simplest type of
merge.

### CODE REVIEW

**Comment by sanderdekoning** [comment]
To others active in the repo could this be the start of implementing `merge` compatibility? (https://github.com/src-d/go-git/blob/master/COMPATIBILITY.md). Is this in development by anyone else? We can help (@john-cai)

**Comment by john-cai** [comment]
@sanderdekoning yes, that's the goal. I wanted to start out with the simplest version and then iterate forward. I think next would be implementing the non-ff 3-way merge

**Comment by sanderdekoning** [comment]
That's great! I'll gladly try to assist and contribute. Do note that I'm new to this repository. Who would you say can assist where necessary/provide code review @john-cai? (@mcuadros?)

**Comment by john-cai** [comment]
@sanderdekoning yes, a review sounds like a good start.

**Comment by DrewFromIQ** [comment]
Merge functionality would be very helpful for a project I'm working on at the moment. Would it be possible to get this PR completed? @mcuadros @smola

**Comment by rcontreras-te** [comment]
`--ff-only` merge would at least be a start.  Just wondering why the PR hasn't even been considered, one way or the other, for... almost 11 months?

**Comment by john-cai** [comment]
@mcuadros could you consider reviewing this PR?

**Comment by fhochleitner** [comment]
we would also very much appreciate a way of (at least) ff merging in the library. as we are implementing something for automatic merges during workflows and hate to escape from standard go implementation to command execution

**Comment by john-cai** [comment]
@pjbgf would you mind reviewing and merging this one as it's been around for quite some time? thank you!

**Comment by pjbgf** [comment]
@john-cai I had a quick look on your PR and here's some initial feedback:

- Although this PR only supports FF, it is important to make clear what the long-term API to support all merge options would look like, so that we ensure backwards compatibility as those features are implemented. `MergeOptions.FFOnly` as `boolean` seems quite restrictive, and does not seem to match the patterns we use across similar APIs (e.g. [ResetMode](https://github.com/go-git/go-git/blob/1dbd729a387edb61c89f088cd68040085e6c81bb/options.go#L353-L375)).
- Making `IsFastForward` public where it is does not feel like idiomatic Go code. I think it would probably be better placed as a method of `EncodedObjectStorer`. 
- The `compatibility.md` should be updated as part of this PR.

**Comment by patgmiller** [comment]
@john-cai are you still working on this? I might be interested in contributing to `merge` features  and prefer not to duplicate efforts.

**Comment by oshiro3** [comment]
Many people, including myself, are looking forward to the merge feature being implemented in go-git.
But the merge functionality is huge and needs to be built on a series of small goals.
Perhaps the MergeOptions structure discussed in this PR should be the first thing to be decided rather than making it smaller.
Rather than continuing the discussion in this PR, I think we should open a discussion or some other place to determine the first goal for the implementation of the merge functionality.

**Comment by pjbgf** [comment]
Closing in favour of #1044.

**Pull request closed without merging**
