### PR TITLE
add r.LogRange() similar to: git log ref1..ref2

### LINKED ISSUE #69: how to git log between two branches
Is there a way to do the equivalent of git log master...my/branch?
Very new to this package, but really only seeing timestamps as a way to limit log results. 

My goal is to iterate through all the commit messages between my current branch and master

### PR DESCRIPTION
**Pull request by ilius**
This fixes #69

### CODE REVIEW

**Comment by ilius** [comment]
I think I made a mistake in the algorithm. Closing this for now.

**Comment by marcusholl** [comment]
@ilius : I have a use-case where I need the equivalent to `git log ref1..ref2`. Is there any other option with the current state of the coding in go-git how this can be done?

**Comment by ilius** [comment]
I'm not sure.
Someone suggested something on
https://github.com/go-git/go-git/issues/69

**Comment by marcusholl** [comment]
@ilius : thanks for the fast response ...

**Pull request closed without merging**
