### PR TITLE
.gitignore fix

### PR DESCRIPTION
**Pull request by ZerGo0**
It should now work when that file has more than 1 line.

### CODE REVIEW

**Comment by ZerGo0** [comment]
#91

**Comment by mcuadros** [comment]
Thanks for the PR, can you provide a test?

**Comment by ZerGo0** [comment]
> Thanks for the PR, can you provide a test?

I'm currently not able to provide a test, but it's pretty self-explanatory. Create a .gitignore file with more than one line for example:
`*.log
*.test`

And create a file named debug.log or debug.test, then do a worktree.status() and it will return both files as untracked even tho they should be ignore. Applying this patch should fix that.

I can provide a test later if no one confirms it until then.

**Comment by ZerGo0** [comment]
@mcuadros Test results:
Without the fix:
```
2020/06/22 18:58:04 =================================================
2020/06/22 18:58:04 Files in directory:
2020/06/22 18:58:04 .git
2020/06/22 18:58:04 .gitignore
2020/06/22 18:58:04 Debug.log
2020/06/22 18:58:04 Debug.test
2020/06/22 18:58:04 go-git-test.go
2020/06/22 18:58:04 =================================================
2020/06/22 18:58:04 .gitignore content:
2020/06/22 18:58:04 *.log
2020/06/22 18:58:04 *.123
2020/06/22 18:58:04 =================================================
2020/06/22 18:58:04 go-git status:
2020/06/22 18:58:04 ? .gitignore
2020/06/22 18:58:04 ? Debug.log
2020/06/22 18:58:04 ? Debug.test
2020/06/22 18:58:04 ? go-git-test.go
2020/06/22 18:58:04 =================================================
2020/06/22 18:58:04 git status:
2020/06/22 18:58:05 ?? .gitignore
2020/06/22 18:58:05 ?? Debug.test
2020/06/22 18:58:05 ?? go-git-test.go
2020/06/22 18:58:05 =================================================
```

With the fix:
```
2020/06/22 18:56:57 =================================================
2020/06/22 18:56:57 Files in directory:
2020/06/22 18:56:57 .git
2020/06/22 18:56:57 .gitignore
2020/06/22 18:56:57 Debug.log
2020/06/22 18:56:57 Debug.test
2020/06/22 18:56:57 go-git-test.go
2020/06/22 18:56:57 =================================================
2020/06/22 18:56:57 .gitignore content:
2020/06/22 18:56:57 *.log
2020/06/22 18:56:57 *.123
2020/06/22 18:56:57 =================================================
2020/06/22 18:56:57 go-git status:
2020/06/22 18:56:57 ? .gitignore
2020/06/22 18:56:57 ? Debug.test
2020/06/22 18:56:57 ? go-git-test.go
2020/06/22 18:56:57 =================================================
2020/06/22 18:56:57 git status:
2020/06/22 18:56:57 ?? .gitignore
2020/06/22 18:56:57 ?? Debug.test
2020/06/22 18:56:57 ?? go-git-test.go
2020/06/22 18:56:57 =================================================
```

**Comment by ZerGo0** [comment]
This fix should probably be applied when the patterns get read into memory instead of just applying it to the ``simpleNameMatch`` function. I can do that next weekend, got no time during the week to debug stuff like this.

**Comment by mcuadros** [comment]
@ZerGo0 the test should follow the project guidelines and use the same frameworks as the whole project.

**Comment by ZerGo0** [comment]
#115 Seems like a proper fix

**Pull request closed without merging**
