### PR TITLE
cli: separate go module for cli

### PR DESCRIPTION
**Pull request by aymanbagabas**
Supersedes https://github.com/go-git/go-git/pull/913

### CODE REVIEW

**Review by pjbgf — APPROVED** [review]

**Comment by pjbgf** [comment]
@aymanbagabas thanks for working on this. :1st_place_medal:

**Comment by clausecker** [comment]
The module name for the new `go-cli` module is bogus and prevents installation of the port through `go install`:

```
go install github.com/go-git/v5/go-git/cli/go-git@latest
go: github.com/go-git/v5/go-git/cli/go-git@latest: module github.com/go-git/v5/go-git/cli/go-git: git ls-remote -q origin in /usr/home/fuz/src/go/pkg/mod/cache/vcs/90742635eba302ad6cafea57b9c6aa099e46a3ff8241bdeb582c371d2615acf8: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

This is likely because you have placed the `v5` into the wrong position.  See also bug #952.  Please fix the module name.

**Comment by VVD** [comment]
How to build go-git after this change?
Old value was:
```
GO_MODULE=     github.com/go-git/go-git/v5
GO_TARGET=      ./cli/go-git
```
New tried different and can't find correct.

**Comment by aymanbagabas** [comment]
> How to build go-git after this change?
> 
> Old value was:
> 
> ```
> 
> GO_MODULE=     github.com/go-git/go-git/v5
> 
> GO_TARGET=      ./cli/go-git
> 
> ```
> 
> For new tried different values and can't find correct.

Hi @VVD! With the new upcoming v6 changes, the gogit module has moved to https://github.com/go-git/cli. Meanwhile, if you still want to use the current v5 cli, you could try using 

```
GO_MODULE=     github.com/go-git/go-git/cli/v5
```

**Comment by clausecker** [comment]
The problem is that you need to tag a release for the new Go module.  The current tags apply to the module in the root directory of the reposity as far as Go is concerned; it doesn't see any tags that apply to the subdirectory.  See the documentation for what the tag needs to look like.

**Comment by VVD** [comment]
> Hi @VVD! With the new upcoming v6 changes, the gogit module has moved to https://github.com/go-git/cli. Meanwhile, if you still want to use the current v5 cli, you could try using
> 
> ```
> GO_MODULE=     GO_MODULE=     github.com/go-git/go-git/cli/go-git
> ```

```
=> Attempting to fetch https://proxy.golang.org/github.com/go-git/go-git/cli/go-git/@v/v5.16.0.mod
fetch: https://proxy.golang.org/github.com/go-git/go-git/cli/go-git/@v/v5.16.0.mod: Not Found
```

**Comment by VVD** [comment]
> Hi @VVD! With the new upcoming v6 changes, the gogit module has moved to https://github.com/go-git/cli.

Hello!
This repo doesn't have releases/tags.
Also I can't fetch it too:
```
=> Attempting to fetch https://proxy.golang.org/github.com/go-git/cli/v6/@v/v6.0.0.mod
fetch: https://proxy.golang.org/github.com/go-git/cli/v6/@v/v6.0.0.mod: Not Found
```
```
DISTVERSION=    6.0.0
GO_MODULE=      github.com/go-git/cli/v6
GO_TARGET=      .
```
Tried 6.0 too.
And `GO_MODULE=github.com/go-git/cli` too.

**Pull request merged**
